### ISSUE TITLE
Update _config.yml Author Information

### ISSUE THREAD

**Issue by indiv0** [PistonDevelopers/blog.piston.rs#3]
Currently the _config.yml lists the author as:

```
author:
    name: Mark Otto
    url: https://twitter.com/mdo
    email: markdotto@gmail.com
```

What should this be changed to?

I think that just putting in PistonDevelopers info should be sufficient.

For example:

```
author:
    name: 'PistonDevelopers'
    url: http://piston.rs
    email: contact@piston.rs
```

On that note, what is the official Piston contact email?
